In [1]:
import numpy as np
import scanpy as sc

from scib_metrics.benchmark import Benchmarker,BioConservation

%matplotlib inline
import matplotlib
from scib_metrics.nearest_neighbors import NeighborsOutput

In [2]:
adata=sc.read("../../imporatant_process_data/4.12_wt_integrate_SCRAN_log1p_gene_filtered.h5ad")


In [3]:
import os

directory = "../processed_data/hypertune/"

files = os.listdir(directory)
varList=list()

for file in files:
    print(os.path.join(directory, file))
    var_name = "scANVI_" + file.split("/")[-1].split("_")[1] + "_" + file.split("/")[-1].split("_")[3]
    print(var_name)
    varList.append(var_name)

../processed_data/hypertune/gene_8000_latent_10_umap.h5ad
scANVI_8000_10
../processed_data/hypertune/gene_1500_latent_15_umap.h5ad
scANVI_1500_15
../processed_data/hypertune/gene_3000_latent_15_umap.h5ad
scANVI_3000_15
../processed_data/hypertune/gene_3000_latent_30_umap.h5ad
scANVI_3000_30
../processed_data/hypertune/gene_2000_latent_10_umap.h5ad
scANVI_2000_10
../processed_data/hypertune/gene_1000_latent_15_umap.h5ad
scANVI_1000_15
../processed_data/hypertune/gene_3000_latent_4_umap.h5ad
scANVI_3000_4
../processed_data/hypertune/gene_4000_latent_4_umap.h5ad
scANVI_4000_4
../processed_data/hypertune/gene_1500_latent_6_umap.h5ad
scANVI_1500_6
../processed_data/hypertune/gene_3000_latent_20_umap.h5ad
scANVI_3000_20
../processed_data/hypertune/gene_4000_latent_20_umap.h5ad
scANVI_4000_20
../processed_data/hypertune/gene_4000_latent_15_umap.h5ad
scANVI_4000_15
../processed_data/hypertune/gene_5000_latent_15_umap.h5ad
scANVI_5000_15
../processed_data/hypertune/gene_8000_latent_4_umap.h5ad


In [4]:
varList

['scANVI_8000_10',
 'scANVI_1500_15',
 'scANVI_3000_15',
 'scANVI_3000_30',
 'scANVI_2000_10',
 'scANVI_1000_15',
 'scANVI_3000_4',
 'scANVI_4000_4',
 'scANVI_1500_6',
 'scANVI_3000_20',
 'scANVI_4000_20',
 'scANVI_4000_15',
 'scANVI_5000_15',
 'scANVI_8000_4',
 'scANVI_5000_30',
 'scANVI_1500_20']

In [5]:
# update adata.obsm dictionary with the loaded data
for file in files:
    # extract the variable name from the file path
    var_name = "scANVI_" + file.split("/")[-1].split("_")[1] + "_" + file.split("/")[-1].split("_")[3]
    # read the data file
    data = sc.read(os.path.join(directory, file))
    # update the adata.obsm dictionary
    adata.obsm[var_name] = data.X

In [6]:
adata

AnnData object with n_obs × n_vars = 274670 × 2000
    obs: 'orig.ident', 'nCount_originalexp', 'nFeature_originalexp', 'Sample', 'Project', 'Limb.Atlas', 'Organ', 'Tissue', 'Tissue.Specific.', 'Stage', 'Gene.type', 'Treatment', 'Age', 'Age.In.Detail.', 'Machine', 'Species', 'Isolation.approach', 'Digestion', 'Enzymes', 'Cre', 'Bone.Forming.Methods', 'Data.Source', 'Related.Assay', 'Origin', 'nCount_RNA', 'nFeature_RNA', 'paper_label', 'coarse_label', 'scDblFinder_class', 'short_id', 'temp_cluster', 'batch', 'K2', 'K6', 'K12', 'K24', 'K53', 'K2.1', 'K6.1', 'K12.1', 'K24.1', 'K53.1', 'K2.2', 'K6.2', 'K12.2', 'K24.2', 'K53.2', 'K2.3', 'K6.3', 'K12.3', 'K24.3', 'K53.3', 'C2', 'C6', 'C12', 'C21', 'C41', 'C2_named', 'C6_named', 'C12_named', 'C21_named', 'C41_named', 'K4', 'K11', 'K25', 'K57', 'C4', 'C9', 'C22', 'C42', 'C4_named', 'C9_named', 'C22_named', 'C42_named', 'K5', 'K19', 'K65', 'C17', 'C36', 'C5', 'C5_named', 'C17_named', 'C36_named', 'batch_atlas', 'size_factors', 'n_genes_by_coun

In [7]:
biocons = BioConservation(isolated_labels=False)
bm = Benchmarker(
    adata,
    batch_key="batch",
    label_key="coarse_label",
    embedding_obsm_keys=varList[8:16],
    bio_conservation_metrics=biocons,
    n_jobs=8,
)


In [8]:
varList[8:16]

['scANVI_1500_6',
 'scANVI_3000_20',
 'scANVI_4000_20',
 'scANVI_4000_15',
 'scANVI_5000_15',
 'scANVI_8000_4',
 'scANVI_5000_30',
 'scANVI_1500_20']

In [9]:
bm.benchmark()

Metrics:   0%|          | 0/10 [00:00<?, ?it/s]/home/zhangyufeng/.local/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:389: RuntimeWarning: overflow encountered in long_scalars
  return 2. * (tp * tn - fn * fp) / ((tp + fn) * (fn + tn) +
/home/zhangyufeng/.local/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:390: RuntimeWarning: overflow encountered in long_scalars
  (tp + fp) * (fp + tn))
/home/zhangyufeng/.local/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:389: RuntimeWarning: overflow encountered in long_scalars
  return 2. * (tp * tn - fn * fp) / ((tp + fn) * (fn + tn) +
/home/zhangyufeng/.local/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:390: RuntimeWarning: overflow encountered in long_scalars
  (tp + fp) * (fp + tn))
/home/zhangyufeng/.local/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:389: RuntimeWarning: overflow encountered in long_scalars
  return 2. * (tp * tn - fn * f

XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

In [11]:
adata

AnnData object with n_obs × n_vars = 274670 × 2000
    obs: 'orig.ident', 'nCount_originalexp', 'nFeature_originalexp', 'Sample', 'Project', 'Limb.Atlas', 'Organ', 'Tissue', 'Tissue.Specific.', 'Stage', 'Gene.type', 'Treatment', 'Age', 'Age.In.Detail.', 'Machine', 'Species', 'Isolation.approach', 'Digestion', 'Enzymes', 'Cre', 'Bone.Forming.Methods', 'Data.Source', 'Related.Assay', 'Origin', 'nCount_RNA', 'nFeature_RNA', 'paper_label', 'coarse_label', 'scDblFinder_class', 'short_id', 'temp_cluster', 'batch', 'K2', 'K6', 'K12', 'K24', 'K53', 'K2.1', 'K6.1', 'K12.1', 'K24.1', 'K53.1', 'K2.2', 'K6.2', 'K12.2', 'K24.2', 'K53.2', 'K2.3', 'K6.3', 'K12.3', 'K24.3', 'K53.3', 'C2', 'C6', 'C12', 'C21', 'C41', 'C2_named', 'C6_named', 'C12_named', 'C21_named', 'C41_named', 'K4', 'K11', 'K25', 'K57', 'C4', 'C9', 'C22', 'C42', 'C4_named', 'C9_named', 'C22_named', 'C42_named', 'K5', 'K19', 'K65', 'C17', 'C36', 'C5', 'C5_named', 'C17_named', 'C36_named', 'batch_atlas', 'size_factors', 'n_genes_by_coun

In [10]:
for embed in varList:
  print(embed)
  print(adata.obsm[embed].shape)
  print(np.unique(adata.obsm[embed], axis=0).shape)

scANVI_8000_10
(274670, 10)
(273479, 10)
scANVI_1500_15
(274670, 15)
(273479, 15)
scANVI_3000_15
(274670, 15)
(273479, 15)
scANVI_3000_30
(274670, 30)
(273479, 30)
scANVI_2000_10
(274670, 10)
(273479, 10)
scANVI_1000_15
(274670, 15)
(273479, 15)
scANVI_3000_4
(274670, 4)
(273479, 4)
scANVI_4000_4
(274670, 4)
(273479, 4)
scANVI_1500_6
(274670, 6)
(273479, 6)
scANVI_3000_20
(274670, 20)
(273479, 20)
scANVI_4000_20
(274670, 20)
(273479, 20)
scANVI_4000_15
(274670, 15)
(273479, 15)
scANVI_5000_15
(274670, 15)
(273479, 15)
scANVI_8000_4
(274670, 4)
(273479, 4)
scANVI_5000_30
(274670, 30)
(273479, 30)
scANVI_1500_20
(274670, 20)
(273479, 20)


In [16]:
np.unique(adata.obsm[embed], axis=0)

array([[-3.0533633e+00, -2.5918239e-01,  1.2213861e+00, ...,
         1.9225857e-01,  1.7524362e-03,  1.6265273e-02],
       [-2.8494253e+00, -1.7095826e+00,  7.9961157e-01, ...,
        -5.9744012e-01, -5.1554418e-01,  2.5330967e-01],
       [-2.8441525e+00,  2.7546060e-01,  2.0584798e+00, ...,
        -1.7046844e+00,  6.3614273e-01, -4.0326414e-01],
       ...,
       [ 5.9371586e+00, -7.3823911e-01,  1.4137859e+00, ...,
        -1.1973939e+00, -2.0977948e+00,  1.6339972e+00],
       [ 5.9654741e+00, -1.4043847e+00,  1.5027944e+00, ...,
        -1.5019494e+00, -2.8410308e+00,  1.9135022e+00],
       [ 6.4117298e+00, -1.1852045e+00,  1.7255412e+00, ...,
        -8.7169111e-01, -1.9057884e+00,  1.9017529e+00]], dtype=float32)

In [18]:
unique_rows, indices = np.unique(adata.obsm[embed], axis=0, return_index=True)

In [30]:
indiceList=[]
for var in varList:
    _,indices=np.unique(adata.obsm[var], axis=0, return_index=True)
    indiceList.append(indices)
common_values = indiceList[0]
for arr in indiceList[1:]:
    common_values = np.intersect1d(common_values, arr)

In [33]:
np.flip(common_values)

array([274669, 274668, 274667, ...,      2,      1,      0])

In [38]:
adata.obs.size

26642990

In [41]:
adata.obs["Age"]

array([False, False, False, ...,  True,  True,  True])

In [45]:
mask = np.ones(adata.obs["Age"].size, dtype=bool)
mask[common_values] = False


In [49]:
adata=adata[common_values,]